In [9]:
mystr = input('Enter string to count characters ')
s = set(mystr)
mydict = {}
for i in s:
    mydict[i]=mystr.count(i)
print(mydict)
for i in sorted(mydict.keys()):
    print("Number of ocurrences of '" + str(i) + "': " + str(mydict[i]))

Enter string to count characters mukul
{'u': 2, 'l': 1, 'k': 1, 'm': 1}
Number of ocurrences of 'k': 1
Number of ocurrences of 'l': 1
Number of ocurrences of 'm': 1
Number of ocurrences of 'u': 2


In [25]:
sing = {'Mukul', 'Tanishq', 'Prateek'}
dance = {'Parth', 'Bhavadeep', 'Manavv', 'Tanishq'}
print(sing.union(dance))
print(sing.intersection(dance))
print(dance.difference(sing))

{'Bhavadeep', 'Parth', 'Mukul', 'Tanishq', 'Manavv', 'Prateek'}
{'Tanishq'}
{'Parth', 'Bhavadeep', 'Manavv'}


## Tuple

In [44]:
temp_tuple = (1,24,23,5342,653,453,45,435,346,34,5)
t_half = int(len(temp_tuple)/2)
print(temp_tuple[:t_half])
print(temp_tuple[t_half:])
print(tuple(x for x in temp_tuple if x%2 == 0))
temp_tuple2 = (234,23,423,4)
print(temp_tuple+temp_tuple2)
print(list(zip(temp_tuple,temp_tuple2)))


(1, 24, 23, 5342, 653)
(453, 45, 435, 346, 34, 5)
(24, 5342, 346, 34)
(1, 24, 23, 5342, 653, 453, 45, 435, 346, 34, 5, 234, 23, 423, 4)
[(1, 234), (24, 23), (23, 423), (5342, 4)]


# Numpy

In [3]:
import numpy

size = 100000
my_arr = numpy.arange(size)
my_list = list(range(size))
%time for _i in range(100): my_arr = my_arr * 2
%time for _i in range(100): my_list2 = [x*2 for x in my_list]

CPU times: user 20 ms, sys: 0 ns, total: 20 ms
Wall time: 21.1 ms
CPU times: user 588 ms, sys: 16 ms, total: 604 ms
Wall time: 606 ms


## Container Volumes

In [6]:
import numpy as np

seed = 0
n = 10
l_limit = 5
u_limit = 25

np.random.seed(seed)
cylinders = np.random.randint(l_limit, u_limit, n)

1

In [15]:
print(cylinders.dtype)
print(cylinders.ndim)
print(cylinders.size)
print(cylinders.shape)

int64
1
10
(10,)


In [38]:
rows = 5
cols = 2
container = cylinders.reshape(rows, cols)

In [22]:
radius = container[:,0]
height = container[:,1]
volume = np.pi*(radius**2)*height

In [33]:
total_volume = volume.sum()
maxvol_index = volume.argmax()

In [32]:
print(np.mean(volume))
print(np.median(volume))
print(np.std(volume))

10186.928338530264
14778.051842486386
7199.758245451731


## More Examples

In [62]:
data = [1,44,543,5.4,2342]
print(np.array(data, dtype = np.float64))
print(np.zeros(10, dtype = np.int64))
print(np.ones((10,10)))
print(np.identity(10))
print(np.arange(100, step=2))

[1.000e+00 4.400e+01 5.430e+02 5.400e+00 2.342e+03]
[0 0 0 0 0 0 0 0 0 0]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [68]:
my_arr = np.arange(11,100,11)
my_arr = my_arr.reshape(3,3)
my_arr[:,2]

array([33, 66, 99])