In [ ]:
import numpy as np

In [1]:
import numpy as np
my_arr = np.arange(100000)
my_list = list(range(1000000))
%time for _ in range(10) : my_arr = my_arr*2
%time for _ in range(10) : my_list = [x*2 for x in my_list]


CPU times: user 4 ms, sys: 0 ns, total: 4 ms
Wall time: 2.73 ms
CPU times: user 460 ms, sys: 88 ms, total: 548 ms
Wall time: 545 ms


In [26]:
import numpy as np
n=10
l_limit=5
u_limit=25
np.random.seed(14)
cyl=np.random.randint(l_limit,u_limit,n)
print(cyl)
cyl.ndim #gives the dimension of array
cyl.dtype #gives the data type of array
cyl.size #gives the number of elements in an array
cyl.shape #gives the no. of elements in all dimensions
container=cyl.reshape(5,2)
print(container)
radius=container[:,0]
height=container[:,1]
vol=np.pi*(radius**2)*height
print(vol)
total_vol=vol.sum()
print(total_vol)
print(vol.max())
print(vol.argmax())

[16 17 12 11 15 15 21 13 18 16]
[[16 17]
 [12 11]
 [15 15]
 [21 13]
 [18 16]]
[13672.21122842  4976.28276329 10602.87520587 18010.75068303
 16286.01631621]
63548.13619681433
18010.750683030285
3


In [104]:
data=[1,2,23,3,2.2]
arr1=np.array(data,dtype=np.int32)
print(arr1)
np.asarray(arr1)
arr2=np.empty(10)
print(arr2)

[ 1  2 23  3  2]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [113]:
import numpy as np
arr=[np.arange(11,44,11),np.arange(44,77,11),np.arange(77,101,11)]
arr1=np.array(arr,dtype=np.int32)
print(arr1)
three=arr1[:,2]
print(three)

[[11 22 33]
 [44 55 66]
 [77 88 99]]
[33 66 99]
